### PR TITLE
Support having a NSViewController conform to View protocol

### PR DESCRIPTION
**Pull request by alanjrogers**
This is to allow a NSViewController to be returned from a `ViewBinding`

I'm not 100% sold on this change, put putting it up for comments.

### CODE REVIEW

**Comment by wkiefer** [comment]
After some thought, I support this — seems reasonable for now until we do some work to make ergonomics of non-scrollable use cases better.

We can see if @danielrhammond agrees.

@alanjrogers would you mind finding a good place to document/comment this is supported? Maybe in the CVC class docs?

**Comment by danielrhammond** [comment]
maybe a silly question, but what retains the NSVC in this case? It seems like unless you're separately holding on to it it would get deallocated since we're just holding on to the `view` by adding it as a subview.

**Comment by alanjrogers** [comment]
> maybe a silly question, but what retains the NSVC in this case? It seems like unless you're separately holding on to it it would get deallocated since we're just holding on to the view by adding it as a subview.

That is a good point, in my current use case my custom View binder is retaining it, but I think it makes sense that the `NSCVItem` should retain the `NSVC`, since it needs it to display the item.

**Comment by alanjrogers** [comment]
> maybe a silly question, but what retains the NSVC in this case? It seems like unless you're separately holding on to it it would get deallocated since we're just holding on to the view by adding it as a subview.

Just looked at the code again, and `public var hostedView: View?` holds onto it, and we just add/remove the view as a subview in `will/didSet`

**Comment by alanjrogers** [comment]
> @alanjrogers would you mind finding a good place to document/comment this is supported? Maybe in the CVC class docs?

I think the `View` protocol docs might make more sense? Also wondering if I should add support on iOS for this?

**Comment by alanjrogers** [comment]
ping @wkiefer and @danielrhammond  for 👁

**Comment by danielrhammond** [comment]
Ah, right yeah I had forgotten that the hostedView in this case is the ViewController. Works for me.

**Pull request merged**
