### PR TITLE
Tribute commit to a renowned and red-plaid designer.

### PR DESCRIPTION
**Pull request by wkiefer**

### CODE REVIEW

**Comment by wkiefer** [comment]
image

**Comment by wkiefer** [comment]
image

**Comment by wkiefer** [comment]
image

**Comment by wkiefer** [comment]
cc @iamcalledrob

**Comment by danielrhammond** [comment]
Went ahead and amended your commit with some tweaks design provided us to the sample directory viewer.

**Comment by wkiefer** [comment]
I CC'ed @iamcalledrob but his calendar auto-declined.

**Comment by wkiefer** [comment]
image

**Comment by alanjrogers** [comment]
That hair. 😍

**Pull request closed without merging**
